services:
  application:
    build:
      context: .
    container_name: app-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - SPRING_PROFILE_ACTIVE=docker
    depends_on:
      - db
    volumes:
      - db-data:/var/lib/mysql

  db:
    image: mysql:8.0
    container_name: bdd-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  db-data:

networks:
  social_media:
    driver: bridge