apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sm-app-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/1
    kind: Deployment
    name: sm-app-deploy
